using System.Text;
using site2llms.Core.Models;
using site2llms.Core.Utils;

namespace site2llms.Core.Services.Output;

/// <summary>
/// File-system output writer for page markdown documents and llms.txt index.
/// </summary>
public class FileOutputWriter : IOutputWriter
{
    private readonly LlmsTxtBuilder _llmsTxtBuilder;

    /// <summary>
    /// Initializes writer with an <see cref="LlmsTxtBuilder"/> for index generation.
    /// </summary>
    public FileOutputWriter(LlmsTxtBuilder llmsTxtBuilder)
    {
        _llmsTxtBuilder = llmsTxtBuilder;
    }

    /// <summary>
    /// Writes one summary markdown file under <c>output/&lt;host&gt;/ai/pages</c>.
    /// </summary>
    public async Task<string> WriteSummaryAsync(Uri rootUrl, SummaryResult summaryResult, DateTimeOffset fetchedAt, CancellationToken ct = default)
    {
        var hostFolder = UrlUtils.SafeHost(rootUrl);
        var outputDir = Path.Combine("output", hostFolder, "ai", "pages");
        Directory.CreateDirectory(outputDir);

        var outputPath = Path.Combine(outputDir, summaryResult.FileName);

        // Persist frontmatter + markdown body to make pages self-describing.
        var content = BuildFrontmatter(summaryResult, fetchedAt) + "\n" + summaryResult.Markdown.Trim() + "\n";

        // Collision check
        if (File.Exists(outputPath))
        {
            var existing = await File.ReadAllTextAsync(outputPath, ct);
            if (!existing.Contains($"source_url: \"{TextUtils.EscapeYaml(summaryResult.Url.ToString())}\"", StringComparison.Ordinal))
            {
                throw new InvalidOperationException($"Filename collision detected for '{summaryResult.FileName}' between different source URLs.");
            }
        }

        await File.WriteAllTextAsync(outputPath, content, Encoding.UTF8, ct);
        return outputPath;
    }

    /// <summary>
    /// Writes the host-level <c>llms-full.txt</c> file with the full generated corpus.
    /// </summary>
    /// <param name="rootUrl">url of root page, used to determine output folder</param>
    /// <param name="pages">list of pages to include in the index</param>
    /// <param name="ct">cancellation token</param>
    /// <returns></returns>
    public async Task WriteLlmsFullTxtAsync(Uri rootUrl, IReadOnlyList<SummaryResult> pages, CancellationToken ct = default)
    {
        var hostFolder = UrlUtils.SafeHost(rootUrl);
        var hostDir = Path.Combine("output", hostFolder);
        Directory.CreateDirectory(hostDir);

        var llmsFullTxtPath = Path.Combine(hostDir, "llms-full.txt");
        var orderedPages = pages.OrderBy(p => p.Title, StringComparer.OrdinalIgnoreCase).ToList();

        var sb = new StringBuilder();
        sb.AppendLine($"# llms-full.txt for {rootUrl.Host}");
        sb.AppendLine();
        sb.AppendLine($"Site root: {rootUrl}");
        sb.AppendLine("Description: Full AI-friendly corpus generated by site2llms.");
        sb.AppendLine($"Generated at (UTC): {DateTime.UtcNow:O}");
        sb.AppendLine($"Pages included: {orderedPages.Count}");
        sb.AppendLine();

        sb.AppendLine("## Index");
        foreach (var page in orderedPages)
        {
            sb.AppendLine($"- {page.Title}: {rootUrl.GetLeftPart(UriPartial.Authority)}/{page.RelativeOutputPath.Replace("\\", "/")}");
        }

        sb.AppendLine();
        sb.AppendLine("## Pages");
        sb.AppendLine();

        foreach (var page in orderedPages)
        {
            sb.AppendLine("---");
            sb.AppendLine($"Title: {page.Title}");
            sb.AppendLine($"URL: {page.Url}");
            sb.AppendLine($"Content Hash: {page.ContentHash}");
            sb.AppendLine($"Relative Output Path: {page.RelativeOutputPath}");
            sb.AppendLine();
            sb.AppendLine(page.Markdown.Trim());
            sb.AppendLine();
        }

        await File.WriteAllTextAsync(llmsFullTxtPath, sb.ToString(), Encoding.UTF8, ct);
    }

    /// <summary>
    /// Writes the host-level <c>llms.txt</c> index file.
    /// </summary>
    public async Task WriteLlmsTxtAsync(Uri rootUrl, IReadOnlyList<SummaryResult> pages, CancellationToken ct = default)
    {
        var hostFolder = UrlUtils.SafeHost(rootUrl);
        var hostDir = Path.Combine("output", hostFolder);
        Directory.CreateDirectory(hostDir);

        var llmsTxtPath = Path.Combine(hostDir, "llms.txt");
        var content = _llmsTxtBuilder.Build(rootUrl, pages);
        await File.WriteAllTextAsync(llmsTxtPath, content, Encoding.UTF8, ct);
    }

    /// <summary>
    /// Creates YAML frontmatter with provenance and caching metadata.
    /// </summary>
    private static string BuildFrontmatter(SummaryResult summaryResult, DateTimeOffset fetchedAt)
    {
        return $"""
---
title: "{TextUtils.EscapeYaml(summaryResult.Title)}"
source_url: "{TextUtils.EscapeYaml(summaryResult.Url.ToString())}"
fetched_at: "{fetchedAt.UtcDateTime:O}"
content_hash: "{summaryResult.ContentHash}"
generator: "site2llms + Ollama"
---
""";
    }
}
