using System.Text;
using site2llms.Core.Models;

namespace site2llms.Core.Services.Output;

/// <summary>
/// Builds host-level <c>llms.txt</c> content listing generated page summaries.
/// </summary>
public class LlmsTxtBuilder
{
    /// <summary>
    /// Produces deterministic index text ordered by page title.
    /// </summary>
    public string Build(Uri rootUrl, IReadOnlyList<SummaryResult> pages)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# llms.txt for {rootUrl.Host}");
        sb.AppendLine();
        sb.AppendLine($"Site root: {rootUrl}");
        sb.AppendLine("Short description: AI-friendly markdown summaries generated by site2llms.");
        sb.AppendLine();
        sb.AppendLine("## Index");

        // Sort for stable output between runs.
        foreach (var page in pages.OrderBy(p => p.Title, StringComparer.OrdinalIgnoreCase))
        {
            sb.AppendLine($"- {page.Title}: {rootUrl.GetLeftPart(UriPartial.Authority)}/ai/pages/{page.FileName}");
        }

        return sb.ToString();
    }
}
